### ISSUE TITLE
SwiftEmitModule normal x86_64 Emitting\ module\ for\ react_native_commandbar (in target 'react-native-commandbar' from project 'Pods')

### ISSUE THREAD

**Issue by noelzappy** [tryfoobar/react-native-commandbar#3]
I get the following error after installing the library, running `pod install` and tries to run the project.
My RN version is `"react-native": "0.72.10",`

The following build commands failed:
        SwiftEmitModule normal x86_64 Emitting\ module\ for\ react_native_commandbar (in target 'react-native-commandbar' from project 'Pods')
(1 failure)

**Comment by Cavallando** [comment]
Hey @noelzappy! Thanks for opening up an issue!

Unfortunately I'm unable to reproduce this on a fresh app running `react-native@0.72.10` and targeting iOS 13.0. Would you be able to share more information about the iOS version you're targeting?

I see this error has come up [for someone else on 0.72](https://stackoverflow.com/questions/77016890/swiftemitmodule-normal-x86-64-release-build-failure-in-react-native) due to mismatching deployment targets in Release/Debug.

FYI our minimum deployment version for `@commandbar/react-native` is driven by the react-native version you're using on [this line of our podspec](https://github.com/tryfoobar/react-native-commandbar/blob/main/react-native-commandbar.podspec#L14), however CommandBarIOS requires a minimum iOS version of 13.0. We should probably make that more clear in peer dependencies/podspec.

I believe the minimum iOS version by default for `react-native@0.72.10` is iOS 12.4, so you might be able to try putting `platform :ios, '13.0'` at the top of your Podfile and rerunning `pod install`

**Comment by noelzappy** [comment]
@Cavallando The minimum version on my app is actually `15.0`.
Here's my Podfile:
```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, "15.0"
prepare_react_native_project!



flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end




target '<REDACTED>' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target '<REDACTED>' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer,  
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
       config[:reactNativePath],
      :mac_catalyst_enabled => false)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end

```

**Comment by noelzappy** [comment]
I had to reset my cache after updating the iOS minimum version. Works now.
